default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_SERVER'] %>
  port: <%= ENV['DB_PORT'] %>
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
